enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-4.0.1.cjs
