name: CI/CD Obscura Dev
# TODO

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on:
      labels: large-runner-gh

    steps:
      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.skaffold
          key: cicd-dev-${{ github.sha }}
          restore-keys: |
            cicd-dev-${{ github.sha }}
            cicd-dev-

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1-${{ github.sha }}
            ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1-

      - name: Git LFS Pull
        run: git lfs pull

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
        shell: bash

      - name: Configure AWS CLI
        run: |
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_DEFAULT_REGION
          aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name obscura-dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 097733725684.dkr.ecr.eu-west-3.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}

      - name: Build and push Docker images
        run: |
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_DEFAULT_REGION
          envsubst < k8s/development/kafka-ui/configmap-env.template.yaml > k8s/development/kafka-ui/configmap-env.yaml
          skaffold run --filename k8s/development/skaffold.dev.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          AWS_MSK_ALL_SECRET_ACCESS_KEY: ${{ secrets.AWS_MSK_ALL_SECRET_ACCESS_KEY }}
          KAFKA_UI_PASSWORD: ${{ secrets.KAFKA_UI_PASSWORD }}
          AWS_DEFAULT_REGION: eu-west-3
        shell: bash

      - name: Store cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            ~/.skaffold
          key: cicd-dev-${{ github.sha }}

      - name: Store LFS cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1-${{ github.sha }}
